[colors]
background = '#ffffff'
cursor_bg = '#0969da'
cursor_border = '#0969da'
cursor_fg = '#ffffff'
foreground = '#0E1116'
selection_bg = '#dbe9f9'
selection_fg = '#0E1116'
ansi = [
    '#24292f',
    '#cf222e',
    '#116329',
    '#4d2d00',
    '#0969da',
    '#8250df',
    '#1b7c83',
    '#6e7781',
]
brights = [
    '#57606a',
    '#a40e26',
    '#1a7f37',
    '#633c01',
    '#218bff',
    '#a475f9',
    '#3192aa',
    '#8c959f',
]

[colors.indexed]
16 = '#633c01'
17 = '#a40e26'
