[colors]
background = '#ffffff'
cursor_bg = '#044289'
cursor_border = '#044289'
cursor_fg = '#ffffff'
foreground = '#24292f'
selection_bg = '#dbe9f9'
selection_fg = '#24292f'
ansi = [
    '#24292e',
    '#d73a49',
    '#28a745',
    '#dbab09',
    '#0366d6',
    '#5a32a3',
    '#0598bc',
    '#6a737d',
]
brights = [
    '#959da5',
    '#cb2431',
    '#22863a',
    '#b08800',
    '#005cc5',
    '#5a32a3',
    '#3192aa',
    '#d1d5da',
]

[colors.indexed]
16 = '#b08800'
17 = '#cb2431'
