[colors]
background = '#24292e'
cursor_bg = '#c8e1ff'
cursor_border = '#c8e1ff'
cursor_fg = '#24292e'
foreground = '#d1d5da'
selection_bg = '#284566'
selection_fg = '#d1d5da'
ansi = [
    '#586069',
    '#ea4a5a',
    '#34d058',
    '#ffea7f',
    '#2188ff',
    '#b392f0',
    '#39c5cf',
    '#d1d5da',
]
brights = [
    '#959da5',
    '#f97583',
    '#85e89d',
    '#ffea7f',
    '#79b8ff',
    '#b392f0',
    '#56d4dd',
    '#fafbfc',
]

[colors.indexed]
16 = '#ffea7f'
17 = '#f97583'
