[colors]
foreground = '#c0bdb7'
background = '#16151A'
cursor_bg = '#c0bdb7'
cursor_border = '#c0bdb7'
cursor_fg = '#16151A'
selection_bg = '#3c3a35'
selection_fg = '#16151A'
ansi = [
    '#302e28',
    '#cc2443',
    '#2e835f',
    '#886e1f',
    '#267aa3',
    '#8061a0',
    '#128184',
    '#f1eee7',
]
brights = [
    '#3c3a35',
    '#ff9498',
    '#79cca4',
    '#d0b56a',
    '#73c2ee',
    '#c7a7ea',
    '#5ecbce',
    '#fefcf4',
]

[colors.indexed]
16 = '#ff9498'
17 = '#cc2443'
