export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
source ~/.profile
export PATH=/usr/local/bin:$PATH

#GIT AUTOCOMPLETE
if [ -f /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash ]; then
  . /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-completion.bash
fi
 
source /Applications/Xcode.app/Contents/Developer/usr/share/git-core/git-prompt.sh
 
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS="yes"
 
export PROMPT_COMMAND='__git_ps1 "\u@\h:\W" "\\\$ ";'
source /Users/mauro/Dropbox/Configurazioni/linux/liquidprompt/liquidprompt

#ALIAS
alias grep='grep --color=auto'
alias pg-start='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias pg-stop='pg_ctl -D /usr/local/var/postgres stop -s -m fast'
alias ftb_backup='heroku pg:pull HEROKU_POSTGRESQL_JADE_URL ftbbck --app ftbmanager'
alias ftb_dev='heroku pg:pull HEROKU_POSTGRESQL_JADE_URL ftbdev --app ftbmanager'
