[colors]
background = '#16181a'
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#3c4048'
selection_fg = '#ffffff'
ansi = [
    '#16181a',
    '#ff6e5e',
    '#5eff6c',
    '#f1ff5e',
    '#5ea1ff',
    '#bd5eff', 
    '#5ef1ff',
    '#ffffff'
]
brights = [
    '#3c4048',
    '#ff6e5e',
    '#5eff6c',
    '#f1ff5e',
    '#5ea1ff',
    '#bd5eff',
    '#5ef1ff',
    '#ffffff'
]

[colors.indexed]
16 = '#ffbd5e'
17 = '#ff6e5e'
