[colors]
background = '#010102'
cursor_bg = '#c0bdb7'
cursor_border = '#c0bdb7'
cursor_fg = '#010102'
foreground = '#c0bdb7'
selection_bg = '#3c3a35'
selection_fg = '#010102'
ansi = [
    '#302e28',
    '#d01a41',
    '#17865d',
    '#8b6e09',
    '#0a7caa',
    '#9a21e8',
    '#0c8285',
    '#f1eee7',
]
brights = [
    '#3c3a35',
    '#fe989b',
    '#24d998',
    '#e0b316',
    '#5cc6fc',
    '#cea1fd',
    '#19d2d7',
    '#fefcf4',
]

[colors.indexed]
16 = '#d2a920'
17 = '#fb868b'
