#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Lean theme
PROMPT_LEAN_TMUX=""
PROMPT_LEAN_VIMODE="true"
PROMPT_LEAN_VIMODE_FORMAT="%F{yellow}[N]%f "
