#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ALIASES
source $HOME/.zsh_aliases

# BASE 16 https://github.com/chriskempson/base16-shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# TMUXINATOR COMPLETION
source ~/.tmuxinator.zsh

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Spaceship
SPACESHIP_PROMPT_ORDER=(
time          # Time stampts section
user          # Username section
host          # Hostname section
git           # Git section (git_branch + git_status)
battery       # Battery level and status
vi_mode       # Vi-mode indicator
jobs          # Backgound jobs indicator
char          # Prompt character
)

SPACESHIP_RPROMPT_ORDER=(
exec_time     # Execution time
dir           # Current directory section
aws           # Amazon Web Services section
ruby          # Ruby section
haskell       # Haskell Stack section
php           # PHP section
node          # Node.js section
)

export SPACESHIP_PHP_SYMBOL=' '
export SPACESHIP_RUBY_SYMBOL=' '

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# GO
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/Dev/go

# FLUTTER
export PATH="$PATH:$HOME/Dev/flutter/bin"

# ANDROID STUDIO
export PATH="$PATH:/opt/android-studio/bin"

# KITTY
autoload -Uz compinit
compinit
# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
