#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ALIASES
source $HOME/.bash_aliases

# BASE 16 https://github.com/chriskempson/base16-shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# TMUXINATOR COMPLETION
source ~/bin/various/tmuxinator.zsh

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Colorls
# source $(dirname $(gem which colorls))/tab_complete.sh

# Lean
lean_right() {
  if [[ ! -z $RUBY_VERSION ]]; then
    echo " %F{red}[$RUBY_VERSION]%f"
  fi
}
PROMPT_LEAN_RIGHT=lean_right

